Микросетки на флексах для всех страниц
htmlacademy-htmlcss/782277-sedona-33 pull request #6
Opened 2022-02-14 17:29 UTC by MichaelBezz

Задание 5.12. Микросетки на флексах для всех страниц

---
:mortar_board: [Микросетки на флексах для всех страниц](https://up.htmlacademy.ru/htmlcss/33/user/782277/tasks/8)

:boom: https://htmlacademy-htmlcss.github.io/782277-sedona-33/6/

2022-02-14 17:37 UTC, MichaelBezz commented on styles/styles.css
> +  display: grid;
Здесь второй модуль подряд нам говорят, что флекс не подходит для реализации карточек в каталоге, поэтому я изменил на грид. Так как лекция (и задание) по гридам мы получим только сегодня, пока набросал основы, чтобы карточки выстроились по макету. В барбершопе они этот момент, как и момент с формой обходят стороной и говорят, что это будет разобрано в следующих лекциях. Посмотрю, что они интересного расскажут по гридам и как сверстают барбершоп, и в следующем задании дополню верстку карточек по аналогии.

2022-02-15 11:28 UTC, mouxez requested changes

2022-02-15 11:28 UTC, mouxez commented on styles/styles.css
> +  box-sizing: border-box;
как правило box-sizing указывают где-то совсем наверху и потом не переопределяют. предлагаю вынести например в боди это и не трогать больше.
а в остальных местах выпилить

2022-02-15 11:28 UTC, mouxez commented on styles/styles.css
> +  list-style-type: none;
предлагаю рассмотреть вариант общего сброса стилей для маркеров списков. как правило это маркера не используются совсем и было бы удобно где-то наверху указать общие стили для ul

2022-02-15 13:02 UTC, merged